sonar.projectKey=DevOpsAssignment_2024TM93504
sonar.projectName=DevOpsAssignment_2024TM93504
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.login=sqp_e71cf416a1730e24ec8487aa644badff199606d4